### ISSUE TITLE
Elliptic.K does not take negative arguments

### ISSUE THREAD

**Issue by gwater** [nolta/Elliptic.jl#12]
`Elliptic.K(x)` currently raises a `DomainError` for negative `x`.

However, _K(x)_ can be calculated for negative arguments with the existing routine using the identity given in Eq. (11) of [this text](http://analyticphysics.com/Mathematical%20Methods/A%20Miscellany%20of%20Elliptic%20Integrals.htm).

Ideally, `Elliptic.K(x)` would just check for negative `x` and map it to a positive `x` automatically.

**Comment by nolta** [comment]
`K`, `E`, and `ellipke` now accept negative arguments.
