### ISSUE TITLE
conflicts with Base.cd

### ISSUE THREAD

**Issue by hamzaelsaawy** [nolta/Elliptic.jl#16]
Since `Jacobi.cd` conflicts with `Base.cd`, it cannot be imported directly into scope:

```julia
julia> using Elliptic

julia> using Elliptic.Jacobi

julia> sd(0,0)
0.0

julia> cd(0,0)
WARNING: both Jacobi and Base export "cd"; uses of it in module Main must be qualified
ERROR: UndefVarError: cd not defined
Stacktrace:
 [1] top-level scope at none:0

julia> Jacobi.cd(0,0)
1.0
```

One solution would be to `import Base.cd` and extend it, but since they provide unrelated functionality, I am not sure people's appetites for that

**Comment by nolta** [comment]
No, extending `Base.cd` would be wrong, since they're unrelated.

**Comment by hamzaelsaawy** [comment]
👍 
Another option would be to rename them to `jacobipq` or `ellipticpq`, but that does not seem very Julian either.
I vote to modify the readme to warn users and suggest not `using Elliptic.Jacobi` but qualify all uses instead as `Jacobi.pq`    
(or use `cd = Jacobi.cd` if they really want not qualify them)
