### ISSUE TITLE
symbol is deprecated in 0.5

### ISSUE THREAD

**Issue by mzaffalon** [nolta/Elliptic.jl#6]
Warning at https://github.com/nolta/Elliptic.jl/blob/master/src/jacobi.jl#L76

**Comment by djsegal** [comment]
@nolta, any word on this?

// this now breaks test suites using `0.7`

**Comment by nolta** [comment]
I've tagged v0.3.0, and hopefully attobot will pick it up.

**Comment by djsegal** [comment]
So https://github.com/nolta/Elliptic.jl/commit/ff9e2eb06304219ad3936e766b407b09fd64383d seems more like a bandage than a solution?

What needs to get done to make this project work on `v0.6` and `v0.7`? 

Is it really as simple as changing [this line of code](https://github.com/nolta/Elliptic.jl/blob/master/src/jacobi.jl#L76) and getting the test suite to work again?

**Comment by nolta** [comment]
The fix was in 5c65fb2acccc7d48ea563fdfe8fc8b83e97157e8. AFAICT the tests are passing on v0.6 and v0.7:

http://juliarun-ci.s3.amazonaws.com/3776026d4922ed5e9737e4d48cd09c4c4afd2dfa/Elliptic_reverse_dependency_tests.html

**Comment by djsegal** [comment]
Oh sorry, my bad. Thank you!
